#!/bin/bash -e
# Copyright (C) 2015 Square, Inc.
# Copyright (C) 2014 CoreOS

ORG_PATH="github.com/square"
REPO_PATH="${ORG_PATH}/certstrap"

export GOPATH=${PWD}/gopath

rm -f $GOPATH/src/${REPO_PATH}
mkdir -p $GOPATH/src/${ORG_PATH}
ln -s ${PWD} $GOPATH/src/${REPO_PATH}

eval $(go env)

go build -o bin/certstrap ${REPO_PATH}
