#!/bin/bash -e
# Copyright (C) 2015 Square, Inc.
# Copyright (C) 2014 CoreOS

source ./build

# tests package relies on BUILD_TAG to be exported
# BUILD_TAG is set by build script
export BUILD_TAG

go test -v -tags=integration ./...
