#!/bin/bash -e
# Copyright (C) 2015 Square, Inc.

source ./build

if [ -z "$PKG" ]; then
    PKG="depot pkix tests"
fi

# Unit tests
echo
for mod in $PKG; do
  mod_path=$REPO_PATH/$mod
  go test -i $mod_path
  godep go test -v $mod_path
done
