name: CI

on: [push, pull_request]

env:
  GOTOOLCHAIN: local

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # ratchet:actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # ratchet:actions/setup-go@v5
      with:
        go-version-file: go.mod
      id: go

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Build binaries
      run: go build -o . ./...

    - name: Run integration tests
      run: go test -v -tags=integration ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # ratchet:actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # ratchet:actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # ratchet:golangci/golangci-lint-action@v6.5.2

      with:
        version: v1.64.8
        # Exclude deprecated PEM functions from the linter until
        # https://github.com/square/certstrap/issues/124 is resolved
        args: --exclude '(De|En)cryptPEMBlock'

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # ratchet:actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # ratchet:actions/setup-go@v5
      with:
        go-version-file: go.mod
      id: go

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: |
        go test -v ./...

    - name: Build binaries
      run: go build -o . ./...

    - name: Run integration tests
      run: |
        go test -v -tags=integration ./...
